name: Build_Test_action

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  TEST_TAG: test
  

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_USERNAME }}/lwserver
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to Docker to use scout
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - 
        name: Build and load to test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: mode=max
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/lwserver:cache 
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/lwserver:cache  
          tags: ${{ env.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/lwserver:${{ env.TEST_TAG }}
          
      - 
        name: Docker Scout
        
        uses: docker/scout-action@v1.15.1
        with:         
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          organization: ${{ vars.REGISTRY_USERNAME }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: mode=max
          cache-from: |
            type=registry,ref=${{ vars.REGISTRY_USERNAME }}/lwserver:cache 
          cache-to: |
            type=registry,ref=${{ vars.REGISTRY_USERNAME }}/lwserver:cache  
          tags: ${{ env.REGISTRY }}/${{ vars.REGISTRY_USERNAME }}/lwserver:${{ steps.meta.outputs.tags }}
          

          
